//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.28 at 06:20:06 PM IST 
//


package com.hospital.management.soap;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="billId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="consultationFee" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="laboratoryFee" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="pharmacyFee" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="totalAmount" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="paymentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillItem", propOrder = {
    "billId",
    "consultationFee",
    "laboratoryFee",
    "pharmacyFee",
    "totalAmount",
    "paymentStatus",
    "billDate"
})
public class BillItem {

    protected long billId;
    protected double consultationFee;
    protected double laboratoryFee;
    protected double pharmacyFee;
    protected double totalAmount;
    @XmlElement(required = true)
    protected String paymentStatus;
    @XmlElement(required = true)
    protected String billDate;

    /**
     * Gets the value of the billId property.
     * 
     */
    public long getBillId() {
        return billId;
    }

    /**
     * Sets the value of the billId property.
     * 
     */
    public void setBillId(long value) {
        this.billId = value;
    }

    /**
     * Gets the value of the consultationFee property.
     * 
     */
    public double getConsultationFee() {
        return consultationFee;
    }

    /**
     * Sets the value of the consultationFee property.
     * 
     */
    public void setConsultationFee(double value) {
        this.consultationFee = value;
    }

    /**
     * Gets the value of the laboratoryFee property.
     * 
     */
    public double getLaboratoryFee() {
        return laboratoryFee;
    }

    /**
     * Sets the value of the laboratoryFee property.
     * 
     */
    public void setLaboratoryFee(double value) {
        this.laboratoryFee = value;
    }

    /**
     * Gets the value of the pharmacyFee property.
     * 
     */
    public double getPharmacyFee() {
        return pharmacyFee;
    }

    /**
     * Sets the value of the pharmacyFee property.
     * 
     */
    public void setPharmacyFee(double value) {
        this.pharmacyFee = value;
    }

    /**
     * Gets the value of the totalAmount property.
     * 
     */
    public double getTotalAmount() {
        return totalAmount;
    }

    /**
     * Sets the value of the totalAmount property.
     * 
     */
    public void setTotalAmount(double value) {
        this.totalAmount = value;
    }

    /**
     * Gets the value of the paymentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Sets the value of the paymentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentStatus(String value) {
        this.paymentStatus = value;
    }

    /**
     * Gets the value of the billDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillDate() {
        return billDate;
    }

    /**
     * Sets the value of the billDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillDate(String value) {
        this.billDate = value;
    }

}
