//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.12 at 08:06:50 PM IST 
//


package com.hospital.management.soap;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="patientId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="patientName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="totalConsultationFee" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="totalLaboratoryFee" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="totalPharmacyFee" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="grandTotal" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="bills" type="{http://hospital.com/management/soap}BillItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patientId",
    "patientName",
    "totalConsultationFee",
    "totalLaboratoryFee",
    "totalPharmacyFee",
    "grandTotal",
    "bills"
})
@XmlRootElement(name = "GetBillingReportResponse")
public class GetBillingReportResponse {

    protected long patientId;
    @XmlElement(required = true)
    protected String patientName;
    protected double totalConsultationFee;
    protected double totalLaboratoryFee;
    protected double totalPharmacyFee;
    protected double grandTotal;
    protected List<BillItem> bills;

    /**
     * Gets the value of the patientId property.
     * 
     */
    public long getPatientId() {
        return patientId;
    }

    /**
     * Sets the value of the patientId property.
     * 
     */
    public void setPatientId(long value) {
        this.patientId = value;
    }

    /**
     * Gets the value of the patientName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * Sets the value of the patientName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientName(String value) {
        this.patientName = value;
    }

    /**
     * Gets the value of the totalConsultationFee property.
     * 
     */
    public double getTotalConsultationFee() {
        return totalConsultationFee;
    }

    /**
     * Sets the value of the totalConsultationFee property.
     * 
     */
    public void setTotalConsultationFee(double value) {
        this.totalConsultationFee = value;
    }

    /**
     * Gets the value of the totalLaboratoryFee property.
     * 
     */
    public double getTotalLaboratoryFee() {
        return totalLaboratoryFee;
    }

    /**
     * Sets the value of the totalLaboratoryFee property.
     * 
     */
    public void setTotalLaboratoryFee(double value) {
        this.totalLaboratoryFee = value;
    }

    /**
     * Gets the value of the totalPharmacyFee property.
     * 
     */
    public double getTotalPharmacyFee() {
        return totalPharmacyFee;
    }

    /**
     * Sets the value of the totalPharmacyFee property.
     * 
     */
    public void setTotalPharmacyFee(double value) {
        this.totalPharmacyFee = value;
    }

    /**
     * Gets the value of the grandTotal property.
     * 
     */
    public double getGrandTotal() {
        return grandTotal;
    }

    /**
     * Sets the value of the grandTotal property.
     * 
     */
    public void setGrandTotal(double value) {
        this.grandTotal = value;
    }

    /**
     * Gets the value of the bills property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the bills property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBills().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BillItem }
     * 
     * 
     */
    public List<BillItem> getBills() {
        if (bills == null) {
            bills = new ArrayList<BillItem>();
        }
        return this.bills;
    }

}
