//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.13 at 11:26:39 AM IST 
//


package com.hospital.management.soap;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hospital.management.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hospital.management.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPatientMedicalReportRequest }
     * 
     */
    public GetPatientMedicalReportRequest createGetPatientMedicalReportRequest() {
        return new GetPatientMedicalReportRequest();
    }

    /**
     * Create an instance of {@link GetPatientMedicalReportResponse }
     * 
     */
    public GetPatientMedicalReportResponse createGetPatientMedicalReportResponse() {
        return new GetPatientMedicalReportResponse();
    }

    /**
     * Create an instance of {@link MedicalRecordItem }
     * 
     */
    public MedicalRecordItem createMedicalRecordItem() {
        return new MedicalRecordItem();
    }

    /**
     * Create an instance of {@link GetBillingReportRequest }
     * 
     */
    public GetBillingReportRequest createGetBillingReportRequest() {
        return new GetBillingReportRequest();
    }

    /**
     * Create an instance of {@link GetBillingReportResponse }
     * 
     */
    public GetBillingReportResponse createGetBillingReportResponse() {
        return new GetBillingReportResponse();
    }

    /**
     * Create an instance of {@link BillItem }
     * 
     */
    public BillItem createBillItem() {
        return new BillItem();
    }

}
