//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.12 at 08:06:50 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://hospital.com/management/soap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hospital.management.soap;
